import {
  Brain,
  Cloud,
  Code,
  Cpu,
  Database,
  Globe,
  Lock,
  Smartphone,
  Zap,
  Layers,
  Rocket,
  TrendingUp,
} from "lucide-react";
import { Category, FilterType } from "@/app/modules/category/types/types";

export const CATEGORIES: Category[] = [
  {
    id: 1,
    name: "Artificial Intelligence",
    icon: <Brain size={32} />,
    gradient: "from-cyan-500 via-blue-500 to-purple-500",
    articles: 156,
    description: "Machine learning, neural networks, and AI breakthroughs",
    tags: ["Machine Learning", "Deep Learning", "NLP"],
    trending: true,
  },
  {
    id: 2,
    name: "Cloud Computing",
    icon: <Cloud size={32} />,
    gradient: "from-blue-500 via-indigo-500 to-purple-500",
    articles: 142,
    description: "Cloud infrastructure, serverless, and distributed systems",
    tags: ["AWS", "Azure", "Kubernetes"],
    trending: false,
  },
  {
    id: 3,
    name: "Web Development",
    icon: <Code size={32} />,
    gradient: "from-purple-500 via-pink-500 to-rose-500",
    articles: 203,
    description:
      "Frontend frameworks, backend APIs, and full-stack development",
    tags: ["React", "Node.js", "TypeScript"],
    trending: true,
  },
  {
    id: 4,
    name: "Cybersecurity",
    icon: <Lock size={32} />,
    gradient: "from-rose-500 via-red-500 to-orange-500",
    articles: 98,
    description: "Security protocols, encryption, and threat protection",
    tags: ["Encryption", "Pentesting", "Zero Trust"],
    trending: false,
  },
  {
    id: 5,
    name: "Quantum Computing",
    icon: <Cpu size={32} />,
    gradient: "from-orange-500 via-amber-500 to-yellow-500",
    articles: 67,
    description: "Quantum algorithms, qubits, and next-gen processing",
    tags: ["Quantum Algorithms", "Qubits", "IBM Q"],
    trending: true,
  },
  {
    id: 6,
    name: "Blockchain & Web3",
    icon: <Globe size={32} />,
    gradient: "from-green-500 via-emerald-500 to-teal-500",
    articles: 124,
    description: "Decentralized systems, smart contracts, and crypto",
    tags: ["Ethereum", "DeFi", "NFTs"],
    trending: true,
  },
  {
    id: 7,
    name: "Database Systems",
    icon: <Database size={32} />,
    gradient: "from-teal-500 via-cyan-500 to-blue-500",
    articles: 89,
    description: "SQL, NoSQL, distributed databases, and data engineering",
    tags: ["PostgreSQL", "MongoDB", "Redis"],
    trending: false,
  },
  {
    id: 8,
    name: "Mobile Development",
    icon: <Smartphone size={32} />,
    gradient: "from-violet-500 via-purple-500 to-fuchsia-500",
    articles: 134,
    description: "iOS, Android, React Native, and cross-platform apps",
    tags: ["Flutter", "Swift", "Kotlin"],
    trending: false,
  },
  {
    id: 9,
    name: "Edge Computing",
    icon: <Zap size={32} />,
    gradient: "from-fuchsia-500 via-pink-500 to-rose-500",
    articles: 76,
    description: "IoT, edge networks, and distributed computing at the edge",
    tags: ["IoT", "5G", "Edge AI"],
    trending: true,
  },
  {
    id: 10,
    name: "DevOps & SRE",
    icon: <Layers size={32} />,
    gradient: "from-indigo-500 via-blue-500 to-cyan-500",
    articles: 112,
    description: "CI/CD, infrastructure as code, and site reliability",
    tags: ["Docker", "Jenkins", "Terraform"],
    trending: false,
  },
  {
    id: 11,
    name: "Emerging Tech",
    icon: <Rocket size={32} />,
    gradient: "from-pink-500 via-rose-500 to-red-500",
    articles: 94,
    description: "AR/VR, metaverse, and breakthrough innovations",
    tags: ["AR/VR", "Metaverse", "Web 3.0"],
    trending: true,
  },
  {
    id: 12,
    name: "Data Science",
    icon: <TrendingUp size={32} />,
    gradient: "from-cyan-500 via-teal-500 to-green-500",
    articles: 167,
    description: "Analytics, visualization, and data-driven insights",
    tags: ["Python", "Pandas", "Visualization"],
    trending: false,
  },
];

export const FILTERS: FilterType[] = [
  "All",
  "Trending",
  "Most Popular",
  "Recent",
];
