import type { Metadata } from "next";
import "./styles/globals.css";
import "@/app/styles/animations.css";
import Footer from "@/app/shared/components/layout/Footer";
import Header from "@/app/shared/components/layout/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
