import type { Metadata } from "next";
import "@/app/styles/globals.css";
import "@/app/styles/animations.css";
import Header from "@/app/shared/components/layout/Header";
import Footer from "@/app/shared/components/layout/Footer";
import { ReduxProvider } from "@/app/store/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <>
            <Header />
            <main className="flex-1">{children}</main>
            <Footer />
          </>
        </ReduxProvider>
      </body>
    </html>
  );
}
